{{- $fullName := include "veritable-acapy-proxy.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-config
  labels:
    {{- include "veritable-acapy-proxy.labels" . | nindent 4 }}
data:
  port: {{ .Values.config.port | quote }}
  logLevel: {{ .Values.config.logLevel }}
  serviceHost: {{ .Values.config.serviceHost | default $fullName }}
  servicePort: {{ .Values.config.servicePort | quote }}
  acapyAdminService: {{ .Values.config.acapyAdminService }}
  authAudience: {{ .Values.config.authAudience }}
  authIssuer: {{ .Values.config.authIssuer }}
