apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "veritable-acapy-proxy.fullname" . }}-config
  labels:
    {{- include "veritable-acapy-proxy.labels" . | nindent 4 }}
data:
  port: {{ .Values.config.port | quote }}
