apiVersion: v1
kind: Secret
metadata:
  name: {{ include "veritable-acapy-proxy.fullname" . }}-secret
  labels:
    {{- include "veritable-acapy-proxy.labels" . | nindent 4 }}
data:
  acapyApiKey: {{ .Values.config.acapyApiKey | b64enc }}
