apiVersion: v2
name: veritable-acapy-proxy
appVersion: '1.0.0'
description: A Helm chart for veritable-acapy-proxy
version: '1.0.0'
type: application
maintainers:
  - name: digicatapult
    email: opensource@digicatapult.org.uk
    url: www.digicatapult.org.uk
